(() => {
  "use strict";
  const actionLabels={create:"Cadastro",update:"Alteração",delete:"Exclusão",archive:"Arquivamento",reactivate:"Reativação"};
  const entityLabels={employee:"Funcionário",teacher:"Professor",absence:"Afastamento",occurrence:"Ocorrência",timebank:"Banco de horas",document:"Memorando/Ofício"};
  const esc=(value)=>String(value??"").replace(/[&<>"']/g,(c)=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[c]);
  const system=document.querySelector(".nav-group-sistema"),about=system?.querySelector('[data-view="sobre"]'),button=document.createElement("button");
  button.type="button";button.dataset.view="historico";button.textContent="Histórico";if(system)system.insertBefore(button,about||null);
  const view=document.createElement("section");view.id="view-historico";view.className="view";
  view.innerHTML='<div class="card"><h2>Histórico de alterações</h2><div class="notice">Registro administrativo das principais mudanças realizadas nesta unidade. Dados pessoais e conteúdo dos cadastros não são copiados para o histórico.</div><div class="audit-toolbar"><label>Ação<select id="auditAction"><option value="all">Todas</option></select></label><label>Área<select id="auditEntity"><option value="all">Todas</option></select></label><button class="btn light" id="auditRefresh" type="button">Atualizar</button></div><div id="auditList"><div class="empty">Carregando histórico…</div></div></div>';
  document.querySelector("main")?.appendChild(view);let rows=[];
  const option=(value,label)=>`<option value="${esc(value)}">${esc(label)}</option>`;
  function render(){const action=document.getElementById("auditAction").value,entity=document.getElementById("auditEntity").value,filtered=rows.filter(x=>(action==="all"||x.action===action)&&(entity==="all"||x.entity===entity));document.getElementById("auditList").innerHTML=filtered.length?`<div class="audit-list">${filtered.map(x=>{const d=x.details||{},fields=Array.isArray(d.changed_fields)&&d.changed_fields.length?` • ${d.changed_fields.length} campo(s)`:"";return`<div class="audit-item"><div><strong>${esc(actionLabels[x.action]||x.action)}</strong><span class="audit-meta">${esc(entityLabels[x.entity]||x.entity)}${fields}</span></div><div>${esc(d.actor_name||"Usuário")}</div><time class="audit-date">${esc(new Date(x.created_at).toLocaleString("pt-BR"))}</time></div>`}).join("")}</div>`:'<div class="empty">Nenhuma alteração encontrada.</div>'}
  async function load(){const host=document.getElementById("auditList");if(!window.gfpOnline?.canViewAudit?.()){button.hidden=true;host.innerHTML='<div class="empty">Seu perfil não possui acesso a este histórico.</div>';return}button.hidden=false;host.innerHTML='<div class="empty">Carregando histórico…</div>';try{rows=await window.gfpOnline.listAuditLogs(200)||[];const actions=[...new Set(rows.map(x=>x.action))].sort(),entities=[...new Set(rows.map(x=>x.entity))].sort();document.getElementById("auditAction").innerHTML='<option value="all">Todas</option>'+actions.map(x=>option(x,actionLabels[x]||x)).join("");document.getElementById("auditEntity").innerHTML='<option value="all">Todas</option>'+entities.map(x=>option(x,entityLabels[x]||x)).join("");render()}catch(e){host.innerHTML=`<div class="notice error">${esc(e?.message||"Não foi possível carregar o histórico.")}</div>`}}
  button.addEventListener("click",()=>{window.GFP_APP?.showView?.("historico");load()});document.getElementById("auditRefresh").addEventListener("click",load);document.getElementById("auditAction").addEventListener("change",render);document.getElementById("auditEntity").addEventListener("change",render);
  window.DIB_AUDIT={record(action,entity,id,details={}){Promise.resolve(window.gfpOnline?.auditChange?.(action,entity,id,details)).catch((e)=>console.warn("audit",e))},load};button.hidden=!window.gfpOnline?.canViewAudit?.();
})();
