/* Ocorrências e relatório de frequência */
(function(){
const extraSettingsDefaults={endereco:'',telefoneUnidade:'',emailUnidade:'',cidade:'',resp3Nome:'',resp3Rg:'',resp3Cargo:''};
function canonicalOccurrence(o){return{id:o.id||uid(),personType:o.personType==='teacher'?'teacher':'employee',personId:o.personId||'',start:o.start||'',end:o.end||o.start||'',tipo:o.tipo||'Outro',duracao:o.duracao||'',comprovante:o.comprovante||'',rotulo:o.rotulo||'',complemento:o.complemento||'',observacao:o.observacao||'',boHoras:String(o.boHoras||'').replace(',','.'),boUnidade:o.boUnidade||''}}
const baseNormalizeDataV114=normalizeData;
normalizeData=function(obj){const x=baseNormalizeDataV114(obj);x.settings={...extraSettingsDefaults,...(x.settings||{})};x.events=Array.isArray(x.events)?x.events.filter(e=>e&&e.date).map(canonicalEvent):[];x.occurrences=Array.isArray(x.occurrences)?x.occurrences.filter(o=>o&&o.personType&&o.personId&&o.start).map(canonicalOccurrence):[];x.occurrences.sort((a,b)=>a.start.localeCompare(b.start)||nameCollator.compare(serverName(a.personType,a.personId),serverName(b.personType,b.personId)));x.employees=x.employees.map(e=>({...e,situacaoFuncional:e.situacaoFuncional||'Efetivo',observacaoCadastro:e.observacaoCadastro||''}));x.teachers=x.teachers.map(t=>({...t,substituicaoFuncao:t.substituicaoFuncao||'',substituicaoCH:t.substituicaoCH||'',substituicaoUnidade:t.substituicaoUnidade||'',atn5:t.atn5||'',atn20:t.atn20||'',observacaoFrequencia:t.observacaoFrequencia||'',observacaoCadastro:t.observacaoCadastro||''}));return x};
data=normalizeData(data);persistDataOnly(data);

function addDef(arr,key,label){if(!arr.some(x=>x[0]===key))arr.push([key,label])}
addDef(listColumnDefs.employee,'situacaoFuncional','Situação funcional');addDef(registryPrintFields.employee,'situacaoFuncional','Situação funcional');
[['substituicaoFuncao','Função na substituição'],['substituicaoCH','C.H. da substituição'],['substituicaoUnidade','Unidade da substituição'],['atn5','ATN 5%'],['atn20','ATN 20%'],['observacaoFrequencia','Observação da frequência']].forEach(x=>{addDef(listColumnDefs.teacher,x[0],x[1]);addDef(registryPrintFields.teacher,x[0],x[1])});

const baseFillConfigV114=fillConfig;
fillConfig=function(){baseFillConfigV114();const f=document.getElementById('configForm');if(!f)return;Object.keys(extraSettingsDefaults).forEach(k=>{if(f.elements[k])f.elements[k].value=data.settings[k]||''})};
const baseResetFormV114=resetForm;
resetForm=function(id){baseResetFormV114(id);if(id==='occurrenceForm'){const f=document.getElementById(id);if(f){const today=new Date().toISOString().slice(0,10);f.elements.start.value=today;f.elements.end.value=today;toggleOccurrenceMode();updateOccurrencePreview()}}};
const baseSetFormV114=setForm;
setForm=function(formId,obj){baseSetFormV114(formId,obj);if(formId==='occurrenceForm'&&obj.personType&&obj.personId){const f=document.getElementById(formId);f.elements.personKey.value=`${obj.personType}:${obj.personId}`;updateOccurrencePreview()}};
const baseShowViewV114=showView;
showView=function(name){baseShowViewV114(name);if(name==='ocorrencias'){renderOccurrenceOptions();renderOccurrenceTable();toggleOccurrenceMode();updateOccurrencePreview()}if(name==='frequencia')initializeFrequencyDates()};
const baseRenderAllV114=renderAll;
renderAll=function(){baseRenderAllV114();fillConfig();renderOccurrenceOptions();renderOccurrenceFilters();renderOccurrenceTable()};
const baseEditItemV114=editItem;
editItem=function(type,id){if(type==='occurrence'){setForm('occurrenceForm',data.occurrences.find(x=>x.id===id));showView('ocorrencias');return}baseEditItemV114(type,id)};
const baseDeleteItemV114=deleteItem;
deleteItem=async function(type,id){if(type==='occurrence'){const ok=await window.GFP_APP.confirmAction({title:'Excluir ocorrência?',message:'A ocorrência será removida permanentemente.',confirmLabel:'Excluir',danger:true});if(!ok)return;data.occurrences=data.occurrences.filter(x=>x.id!==id);saveData();window.DIB_AUDIT?.record('delete','occurrence',id);return}baseDeleteItemV114(type,id)};
const baseSetPrintModeV114=setPrintMode;
setPrintMode=function(mode){if(mode!=='frequency'){document.body.classList.remove('print-frequency');baseSetPrintModeV114(mode);return}document.body.classList.remove('print-points','print-sector','print-birthday','print-registry','print-frequency');document.body.classList.add('print-frequency');document.getElementById('dynamicPrintPage').textContent='@media print{@page{size:A4 landscape;margin:0}}'};

function renderOccurrenceOptions(){const sel=document.getElementById('occurrencePerson');if(!sel)return;const current=sel.value;const items=[...data.employees.map(x=>({...x,_type:'employee'})),...data.teachers.map(x=>({...x,_type:'teacher'}))].sort((a,b)=>compareNames(a,b)||a._type.localeCompare(b._type));sel.innerHTML='<option value="">Selecione...</option>'+items.map(x=>`<option value="${x._type}:${x.id}">${esc(x.nome)} - ${x._type==='employee'?'Funcionário':'Professor'}${isActive(x)?'':' - INATIVO'}</option>`).join('');if([...sel.options].some(o=>o.value===current))sel.value=current}
function shortDate(v){if(!v)return'';const [y,m,d]=v.split('-');return`${d}/${m}`}
function occurrencePeriod(o){return !o.end||o.end===o.start?shortDate(o.start):`${shortDate(o.start)} a ${shortDate(o.end)}`}
function isBOOccurrence(o){return String(o?.tipo||'').trim().toLocaleUpperCase('pt-BR')==='BO'}
function numberPt(v){const n=Number(String(v||'').replace(',','.'));if(!Number.isFinite(n))return'';return Number.isInteger(n)?String(n):String(Math.round(n*100)/100).replace('.',',')}
function occurrenceText(o){if(!o||!o.start)return'';if(isBOOccurrence(o)){const hours=numberPt(o.boHoras),unit=String(o.boUnidade||'').trim();return`${occurrencePeriod(o)} - BO${hours?` (${hours}h)`:''}${unit?` - ${unit}`:''}`.replace(/\s+/g,' ').trim()}const label=(o.rotulo||o.tipo||'Ocorrência').trim(),duration=(o.duracao||'').trim(),proof=(o.comprovante||'').trim(),extra=(o.complemento||'').trim();return`${occurrencePeriod(o)} - ${label}${duration?` (${duration})`:''}${proof?` ${proof}`:''}${extra?` ${extra}`:''}`.replace(/\s+/g,' ').trim()}
function toggleOccurrenceMode(){const f=document.getElementById('occurrenceForm');if(!f)return;const bo=isBOOccurrence({tipo:f.elements.tipo?.value});document.querySelectorAll('#occurrenceForm .bo-field').forEach(el=>el.classList.toggle('visible',bo));if(f.elements.boHoras)f.elements.boHoras.required=bo;const sel=f.elements.personKey;if(sel){[...sel.options].forEach(opt=>{if(opt.value.startsWith('employee:'))opt.disabled=bo});if(bo&&sel.value.startsWith('employee:'))sel.value=''} }
function updateOccurrencePreview(){const f=document.getElementById('occurrenceForm'),box=document.getElementById('occurrencePreview');if(!f||!box)return;toggleOccurrenceMode();const o=formObj(f);box.textContent=o.start?occurrenceText(o):'Preencha as datas para visualizar o texto.'}
function renderOccurrenceFilters(){const year=document.getElementById('occurrenceYearFilter');if(!year)return;const current=year.value||'all',years=[...new Set(data.occurrences.map(o=>(o.start||'').slice(0,4)).filter(Boolean))].sort((a,b)=>b.localeCompare(a));year.innerHTML='<option value="all">Todos os anos</option>'+years.map(y=>`<option>${y}</option>`).join('');year.value=years.includes(current)?current:'all'}
function occurrenceTableHtml(){const search=(document.getElementById('occurrenceSearch')?.value||'').trim().toLocaleLowerCase('pt-BR'),type=document.getElementById('occurrenceTypeFilter')?.value||'all',year=document.getElementById('occurrenceYearFilter')?.value||'all';let rows=[...data.occurrences].filter(o=>(type==='all'||o.personType===type)&&(year==='all'||o.start.startsWith(year)));if(search)rows=rows.filter(o=>serverName(o.personType,o.personId).toLocaleLowerCase('pt-BR').includes(search));rows.sort((a,b)=>b.start.localeCompare(a.start)||nameCollator.compare(serverName(a.personType,a.personId),serverName(b.personType,b.personId)));if(!rows.length)return'<div class="empty">Nenhuma ocorrência encontrada.</div>';return`<div class="table-wrap"><table class="data"><thead><tr><th>Nome</th><th>Vínculo</th><th>Período</th><th>Tipo / texto</th><th>C.H. BO</th><th>Unidade</th><th>Observação</th><th>Ações</th></tr></thead><tbody>${rows.map(o=>`<tr><td>${esc(serverName(o.personType,o.personId)||'Cadastro não encontrado')}</td><td>${o.personType==='employee'?'Funcionário':'Professor'}</td><td>${esc(occurrencePeriod(o))}</td><td>${esc(occurrenceText(o))}</td><td>${isBOOccurrence(o)?esc(numberPt(o.boHoras)):''}</td><td>${isBOOccurrence(o)?esc(o.boUnidade||''):''}</td><td>${esc(o.observacao||'')}</td><td><button class="mini-btn edit" onclick="editItem('occurrence','${o.id}')">Editar</button> <button class="mini-btn del" onclick="deleteItem('occurrence','${o.id}')">Excluir</button></td></tr>`).join('')}</tbody></table></div>`}
function renderOccurrenceTable(){const box=document.getElementById('occurrenceTable');if(box)box.innerHTML=occurrenceTableHtml()}
const occForm=document.getElementById('occurrenceForm');if(occForm){occForm.addEventListener('submit',e=>{e.preventDefault();const o=formObj(e.target);if(!o.personKey){alert('Selecione um funcionário ou professor.');return}if(o.end<o.start){alert('A data final não pode ser anterior à data inicial.');return}const [personType,personId]=o.personKey.split(':');if(isBOOccurrence(o)&&personType!=='teacher'){alert('BOs podem ser cadastradas somente para professores.');return}if(isBOOccurrence(o)&&!(Number(String(o.boHoras||'').replace(',','.'))>0)){alert('Informe a carga horária da BO.');return}const action=o.id?'update':'create',item=canonicalOccurrence({...o,personType,personId,id:o.id||uid()});if(o.id)Object.assign(data.occurrences.find(x=>x.id===o.id),item);else data.occurrences.push(item);saveData();window.DIB_AUDIT?.record(action,'occurrence',item.id);resetForm('occurrenceForm')});occForm.addEventListener('input',updateOccurrencePreview);occForm.addEventListener('change',updateOccurrencePreview)}
['occurrenceSearch','occurrenceTypeFilter','occurrenceYearFilter'].forEach(id=>document.getElementById(id)?.addEventListener(id==='occurrenceSearch'?'input':'change',renderOccurrenceTable));

function initializeFrequencyDates(){const a=document.getElementById('frequencyStart'),b=document.getElementById('frequencyEnd'),issue=document.getElementById('frequencyIssueDate');if(!a||!b)return;const today=new Date();if(!a.value||!b.value){let end=new Date(today.getFullYear(),today.getMonth(),5,12),start=new Date(end.getFullYear(),end.getMonth()-1,6,12);if(today.getDate()<5){end=new Date(today.getFullYear(),today.getMonth()-1,5,12);start=new Date(end.getFullYear(),end.getMonth()-1,6,12)}const key=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;a.value=key(start);b.value=key(end)}if(issue&&!issue.value)issue.value=today.toISOString().slice(0,10)}
function rangeOverlaps(x,start,end){return x.start<=end&&(x.end||x.start)>=start}
function daysInclusive(start,end){const a=new Date(start+'T12:00:00'),b=new Date(end+'T12:00:00');return Math.max(1,Math.round((b-a)/86400000)+1)}
function canonicalAbsenceLabel(v){const raw=String(v||'Afastamento').trim(),up=raw.toLocaleUpperCase('pt-BR');const map={'FÉRIAS':'Férias','FERIAS':'Férias','LICENÇA':'Licença','LICENCA':'Licença','LICENÇA MÉDICA':'Licença Médica','LICENCA MEDICA':'Licença Médica','LICENÇA SAÚDE':'Licença Saúde','LICENCA SAUDE':'Licença Saúde','LICENÇA MATERNIDADE':'Licença Maternidade','LICENCA MATERNIDADE':'Licença Maternidade','AFASTAMENTO':'Afastamento'};return map[up]||raw}
function absenceReportData(a){const label=canonicalAbsenceLabel(a.rotulo||a.tipo),up=label.toLocaleUpperCase('pt-BR');if(a.indefinite)return{kind:up.includes('FÉRIA')?'vacation':'leave',text:label,observation:''};const days=daysInclusive(a.start,a.end),start=shortDate(a.start),end=shortDate(a.end);if(up.includes('FÉRIA'))return{kind:'vacation',text:`Férias de ${start} à ${end}`,observation:''};if((up==='LICENÇA'||up==='LICENCA')&&days>45)return{kind:'leave',text:'Licença',observation:`Licença até ${formatDatePt(a.end)}`};if(up.includes('MATERNIDADE'))return{kind:'leave',text:`${start}${a.end!==a.start?` a ${end}`:''} - ${label}`,observation:''};return{kind:'leave',text:`${start}${a.end!==a.start?` a ${end}`:''} - ${label} (${days}d)`,observation:''}}
function uniqueLines(lines){const out=[];for(const x of lines.map(v=>String(v||'').trim()).filter(Boolean))if(!out.some(v=>v.toLocaleLowerCase('pt-BR')===x.toLocaleLowerCase('pt-BR')))out.push(x);return out}
function frequencyDataFor(person,type,start,end){const allOcc=data.occurrences.filter(o=>o.personType===type&&o.personId===person.id&&rangeOverlaps(o,start,end)).sort((a,b)=>a.start.localeCompare(b.start)),boOcc=allOcc.filter(isBOOccurrence),occ=allOcc.filter(o=>!isBOOccurrence(o));const abs=data.absences.filter(a=>a.personType===type&&a.personId===person.id&&(a.indefinite||rangeOverlaps(a,start,end))).sort((a,b)=>Number(b.indefinite)-Number(a.indefinite)||(a.start||'').localeCompare(b.start||''));let frequency=occ.map(occurrenceText),observation=occ.map(o=>o.observacao);const absData=abs.map(absenceReportData),vacations=absData.filter(x=>x.kind==='vacation'),leaves=absData.filter(x=>x.kind!=='vacation');frequency.push(...leaves.map(x=>x.text));observation.push(...leaves.map(x=>x.observation));if(vacations.length){if(frequency.length)observation.push(...vacations.map(x=>x.text));else frequency.push(...vacations.map(x=>x.text))}let boHours=0;if(type==='teacher'){boHours=boOcc.reduce((sum,o)=>sum+(Number(String(o.boHoras||'').replace(',','.'))||0),0);observation.push(...uniqueLines(boOcc.map(o=>String(o.boUnidade||'').trim()).filter(Boolean)).map(u=>`Subst. ${u}`));if(person.observacaoFrequencia)observation.push(person.observacaoFrequencia)}frequency=uniqueLines(frequency);observation=uniqueLines(observation);if(!frequency.length)frequency=['Frequente'];return{frequency,observation,boHours}}
function lineHtml(lines){return`<div class="frequency-lines">${lines.map(x=>`<div>${esc(x)}</div>`).join('')}</div>`}
function personWeight(x){return Math.max(1,x._freq.frequency.length,x._freq.observation.length)}
function chunkWeighted(items,max){const pages=[];let page=[],used=0;for(const item of items){const w=Math.min(max,personWeight(item));if(page.length&&used+w>max){pages.push(page);page=[];used=0}page.push(item);used+=w}if(page.length)pages.push(page);return pages}
function frequencyHeader(subtitle,start,end){const s=data.settings,contact=[s.telefoneUnidade?`Fone ${s.telefoneUnidade}`:'',s.emailUnidade?`e-mail: ${s.emailUnidade}`:''].filter(Boolean).join(' - ');return`<div class="frequency-header"><div class="frequency-logo-box"><img src="${logoData}"></div><div class="frequency-head-text"><div class="pref">${esc(s.prefeitura)}</div><div>${esc(s.secretaria)}</div><div class="school">${esc(s.escola)}</div><div>${esc(s.endereco||'')}</div><div class="contact">${esc(contact)}</div><div class="main-title">QUADRO DE FREQUÊNCIA</div><div class="sub-title">${esc(subtitle)}</div><div class="period">PERÍODO: ${formatDatePt(start)} a ${formatDatePt(end)}</div></div></div>`}
function frequencySignatures(issueDate){const s=data.settings,people=[[s.resp1Nome,s.resp1Rg,s.resp1Cargo],[s.resp2Nome,s.resp2Rg,s.resp2Cargo],[s.resp3Nome,s.resp3Rg,s.resp3Cargo]];return`<div class="frequency-date">${esc(s.cidade||'')}, ${longDatePt(issueDate)}.</div><div class="frequency-signatures">${people.map(([n,rg,c])=>`<div class="frequency-signature"><div class="line"></div><div>${esc(n||'')}</div>${rg?`<div>RG ${esc(rg)}</div>`:''}<div>${esc(c||'')}</div></div>`).join('')}</div>`}
function longDatePt(v){if(!v)return'';const [y,m,d]=v.split('-').map(Number);return`${d} de ${monthNames[m-1].toLocaleLowerCase('pt-BR')} de ${y}`}
function employeeFrequencySheet(items,start,end,issue,page,total){const rows=items.map(p=>`<tr><td>${esc(p.nome)}</td><td class="center">${esc(p.matricula||'')}</td><td>${esc(p.cargo||'')}</td><td class="center">${esc(p.situacaoFuncional||'Efetivo')}</td><td class="freq-cell">${lineHtml(p._freq.frequency)}</td><td>${lineHtml(p._freq.observation)}</td></tr>`).join('');return`<section class="frequency-sheet">${frequencyHeader('QUADRO DE APOIO',start,end)}<table class="frequency-table employee-frequency"><colgroup><col class="c-name"><col class="c-mat"><col class="c-role"><col class="c-sit"><col class="c-freq"><col class="c-obs"></colgroup><thead><tr><th>Nome</th><th>Matrícula</th><th>Função</th><th>Sit.</th><th>Frequência</th><th>Observação</th></tr></thead><tbody>${rows}</tbody></table>${frequencySignatures(issue)}<div class="frequency-page-number">Página ${page} de ${total}</div></section>`}
function workloadParts(t){const value=String(t.cargaHoraria||'').trim();if(value.includes('/')){const [sem,men]=value.split('/');return[sem.trim(),men.trim()]}return[String(t.jornada||value||''),String(t.cargaMensal||'')]}
function teacherSituation(t){const v=String(t.situacao||'Efetivo').trim();return /^efet/i.test(v)?'Efet':v}
function teacherFrequencySheet(items,start,end,issue,page,total){const rows=items.map(p=>{const [sem,men]=workloadParts(p),boCH=numberPt(p._freq.boHours);return`<tr><td>${esc(p.nome)}</td><td class="center">${esc(p.matricula||'')}</td><td class="center">${esc(p.categoria||'Professor')}</td><td class="center">${esc(teacherSituation(p))}</td><td class="center">${esc(sem)}</td><td class="center">${esc(men)}</td><td class="freq-cell">${lineHtml(p._freq.frequency)}</td><td class="center">-</td><td class="center">${esc(boCH||'-')}</td><td class="center">${esc(p.atn5||'')}</td><td class="center">${esc(p.atn20||'')}</td><td>${lineHtml(p._freq.observation)}</td></tr>`}).join('');return`<section class="frequency-sheet">${frequencyHeader('PROFESSOR DE EDUCAÇÃO INFANTIL',start,end)}<table class="frequency-table teacher-frequency"><colgroup><col class="c-name"><col class="c-mat"><col class="c-role"><col class="c-sit"><col class="c-sem"><col class="c-men"><col class="c-freq"><col class="c-subf"><col class="c-subch"><col class="c-atn5"><col class="c-atn20"><col class="c-obs"></colgroup><thead><tr><th rowspan="2">NOME</th><th rowspan="2">Matric.</th><th rowspan="2">FUNÇÃO</th><th rowspan="2">Sit.</th><th colspan="2">C. Horária</th><th rowspan="2">FREQUÊNCIA</th><th colspan="2">Subst.</th><th rowspan="2">ATN<br>5%</th><th rowspan="2">ATN<br>20%</th><th rowspan="2">Observação</th></tr><tr><th>SEM</th><th>MEN</th><th>Função</th><th>C.H.</th></tr></thead><tbody>${rows}</tbody></table>${frequencySignatures(issue)}<div class="frequency-page-number">Página ${page} de ${total}</div></section>`}
function orderedFrequencyPeople(type,start,end,order){let arr=(type==='employee'?data.employees:data.teachers).filter(p=>isActive(p)&&(type!=='teacher'||!isSubstitute(p))).map(p=>({...p,_freq:frequencyDataFor(p,type,start,end)}));arr.sort((a,b)=>order==='sector'?sectorOrder.indexOf(a.setor)-sectorOrder.indexOf(b.setor)||compareNames(a,b):compareNames(a,b));return arr}
function generateFrequencyReport(){const start=document.getElementById('frequencyStart').value,end=document.getElementById('frequencyEnd').value,issue=document.getElementById('frequencyIssueDate').value,source=document.getElementById('frequencySource').value,order=document.getElementById('frequencyOrder').value;if(!start||!end||!issue){alert('Informe o período e a data de emissão.');return}if(end<start){alert('A data final não pode ser anterior à data inicial.');return}setPrintMode('frequency');clearPreview();clearReportPreview();let sections=[],counts=[];if(source==='employee'||source==='all'){const people=orderedFrequencyPeople('employee',start,end,order),pages=chunkWeighted(people,23);counts.push(`${people.length} funcionário(s)`);const total=pages.length||1;(pages.length?pages:[[]]).forEach((page,i)=>sections.push(employeeFrequencySheet(page,start,end,issue,i+1,total)))}if(source==='teacher'||source==='all'){const people=orderedFrequencyPeople('teacher',start,end,order),pages=chunkWeighted(people,18);counts.push(`${people.length} professor(es)`);const total=pages.length||1;(pages.length?pages:[[]]).forEach((page,i)=>sections.push(teacherFrequencySheet(page,start,end,issue,i+1,total)))}document.getElementById('frequencyPrintArea').innerHTML=sections.join('');document.getElementById('frequencyControls').style.display='flex';document.getElementById('frequencyCount').textContent=counts.join(' e ')||'Nenhum cadastro';document.getElementById('frequencyControls').scrollIntoView({behavior:'smooth'})}
function clearFrequencyPreview(){document.getElementById('frequencyPrintArea').innerHTML='';document.getElementById('frequencyControls').style.display='none'}
window.generateFrequencyReport=generateFrequencyReport;window.clearFrequencyPreview=clearFrequencyPreview;window.updateOccurrencePreview=updateOccurrencePreview;window.toggleOccurrenceMode=toggleOccurrenceMode;window.initializeFrequencyDates=initializeFrequencyDates;

renderAll();resetForm('occurrenceForm');toggleAbsencePeriodMode();initializeFrequencyDates();
if(location.search.includes('preview=frequency-employees')){showView('frequencia');document.getElementById('frequencyStart').value='2026-06-06';document.getElementById('frequencyEnd').value='2026-07-05';document.getElementById('frequencyIssueDate').value='2026-07-07';document.getElementById('frequencySource').value='employee';setTimeout(generateFrequencyReport,80)}else if(location.search.includes('preview=frequency-teachers')){showView('frequencia');document.getElementById('frequencyStart').value='2026-06-06';document.getElementById('frequencyEnd').value='2026-07-05';document.getElementById('frequencyIssueDate').value='2026-07-07';document.getElementById('frequencySource').value='teacher';setTimeout(generateFrequencyReport,80)}
})();
