(function(){
'use strict';
const cfg=window.GFP_CONFIG||{};
const runtimeVersion='20260804-7';
const state={accessToken:'',refreshToken:'',expiresAt:0,user:null,profile:null,memberships:[],schools:[],adminSchools:[],schoolId:'',actualSchoolId:'',role:'',preview:null,ready:false,saveTimer:null,saving:false,savePromise:null,pendingPayload:null,lastSaved:'',adminUsers:[]};
const configured=()=>/^https:\/\/[^.]+\.supabase\.co$/.test(String(cfg.supabaseUrl||''))&&!String(cfg.anonKey||'').includes('SUA-CHAVE');
const base=()=>String(cfg.supabaseUrl||'').replace(/\/$/,'');
const authKey='gfp_online_auth_v2';
function el(id){return document.getElementById(id)}
function jsonHeaders(auth=true){const h={'apikey':cfg.anonKey,'Content-Type':'application/json'};if(auth&&state.accessToken)h.Authorization='Bearer '+state.accessToken;return h}
function errorText(value,fallback='Ocorreu um erro inesperado.') {if(value instanceof Error)return errorText(value.message,fallback);if(typeof value==='string'&&value.trim()&&value.trim()!=='[object Object]')return value.trim();if(value&&typeof value==='object'){for(const key of ['message','msg','error_description','details','hint','error']){const text=errorText(value[key],'');if(text)return text}try{const text=JSON.stringify(value);if(text&&text!=='{}')return text}catch{}}return fallback}
async function request(path,{method='GET',body,headers={},auth=true}={}){const res=await fetch(base()+path,{method,headers:{...jsonHeaders(auth),...headers},body:body===undefined?undefined:JSON.stringify(body)});let payload=null;const text=await res.text();if(text)try{payload=JSON.parse(text)}catch{payload=text}if(!res.ok)throw new Error(errorText(payload,`Erro ${res.status}. Tente novamente.`));return payload}
function saveSession(){localStorage.setItem(authKey,JSON.stringify({accessToken:state.accessToken,refreshToken:state.refreshToken,expiresAt:state.expiresAt,user:state.user}))}
function clearSession(){localStorage.removeItem(authKey);state.accessToken='';state.refreshToken='';state.expiresAt=0;state.user=null}
function restoreSession(){try{const s=JSON.parse(localStorage.getItem(authKey)||'null');if(s){Object.assign(state,s);return true}}catch{}return false}
async function signIn(email,password){const x=await request('/auth/v1/token?grant_type=password',{method:'POST',body:{email,password},auth:false});state.accessToken=x.access_token;state.refreshToken=x.refresh_token;state.expiresAt=Date.now()+(Number(x.expires_in||3600)*1000);state.user=x.user;saveSession()}
async function refreshSession(){if(!state.refreshToken)throw new Error('Sessão expirada.');const x=await request('/auth/v1/token?grant_type=refresh_token',{method:'POST',body:{refresh_token:state.refreshToken},auth:false});state.accessToken=x.access_token;state.refreshToken=x.refresh_token||state.refreshToken;state.expiresAt=Date.now()+(Number(x.expires_in||3600)*1000);state.user=x.user||state.user;saveSession()}
async function ensureToken(){if(state.accessToken&&Date.now()<state.expiresAt-60000)return;if(state.refreshToken)await refreshSession();else throw new Error('Faça login novamente.')}
async function validateRestoredSession(){await ensureToken();const user=await request('/auth/v1/user');if(!user?.id)throw new Error('Não foi possível validar a sessão salva.');state.user=user;saveSession()}
async function signOut(){try{await flushPendingSave();await request('/auth/v1/logout',{method:'POST',body:{}})}catch(e){if(state.pendingPayload){alert('Não foi possível salvar as alterações no banco. Verifique sua conexão e tente sair novamente.');return}}clearSession();location.reload()}
async function resetPassword(){const email=prompt('Informe o e-mail da conta:');if(!email)return;await request('/auth/v1/recover?redirect_to='+encodeURIComponent(location.origin),{method:'POST',body:{email},auth:false});alert('Se o e-mail estiver cadastrado, o Supabase enviará as instruções de recuperação.')}
function q(v){return encodeURIComponent(v)}
async function rest(table,query='',opts={}){await ensureToken();return request(`/rest/v1/${table}${query?('?'+query):''}`,opts)}
function recoveryFromUrl(){const raw=(location.hash||'').replace(/^#/,'');if(!raw)return false;const hp=new URLSearchParams(raw);if(hp.get('type')!=='recovery'||!hp.get('access_token'))return false;state.accessToken=hp.get('access_token')||'';state.refreshToken=hp.get('refresh_token')||'';state.expiresAt=Date.now()+(Number(hp.get('expires_in')||3600)*1000);saveSession();el('loginForm').style.display='none';el('forgotPasswordBtn').style.display='none';el('recoveryForm').style.display='block';history.replaceState(null,'',location.pathname+location.search);return true}
async function completeRecovery(e){e.preventDefault();const fd=new FormData(e.target),password=String(fd.get('password')||''),confirm=String(fd.get('confirm')||'');if(password.length<8){showAuthError('A senha precisa ter pelo menos 8 caracteres.');return}if(password!==confirm){showAuthError('As senhas não coincidem.');return}try{await request('/auth/v1/user',{method:'PUT',body:{password}});alert('Senha atualizada. Entre novamente com a nova senha.');clearSession();location.reload()}catch(err){showAuthError(err.message)}}
async function loadIdentity(){const uid=state.user?.id;if(!uid)throw new Error('Usuário não identificado.');const profiles=await rest('profiles',`select=id,full_name,system_role,active&id=eq.${q(uid)}`);state.profile=profiles?.[0];if(!state.profile||!state.profile.active)throw new Error('Este usuário está inativo ou não possui perfil no sistema.');if(state.profile.system_role==='master'){
  state.schools=await rest('schools','select=*&active=eq.true&order=name.asc');
  state.memberships=[];state.role='master';
}else{
  state.memberships=await rest('memberships',`select=id,user_id,school_id,role,active,schools(id,name,short_name,code,active)&user_id=eq.${q(uid)}&active=eq.true`);
  state.schools=state.memberships.map(m=>m.schools).filter(Boolean).filter(s=>s.active);
}
if(!state.schools.length&&state.profile.system_role!=='master')throw new Error('Seu usuário não está vinculado a nenhuma escola ativa.');
}
function activeMembership(schoolId){if(state.profile?.system_role==='master')return{role:'master'};return state.memberships.find(m=>m.school_id===schoolId&&m.active)}
function effectiveRole(){return state.preview?.role||state.role||activeMembership(state.schoolId)?.role||''}
function roleLabel(r){return({master:'Administrador Geral',admin:'Administrador da escola',operator:'Operador',consulta:'Consulta'})[r]||r||'Sem permissão'}
function setCloud(text,cls=''){const e=el('cloudStatus');if(e){e.textContent=text;e.className='cloud-status '+cls}if(typeof window.GFP_APP?.refreshDashboard==='function')window.GFP_APP.refreshDashboard()}
function localCacheKey(){return 'gfp_school_cache_'+(state.schoolId||'none')}
function cacheLocal(key,value){try{localStorage.setItem(key,value);return true}catch(e){console.warn('Cópia local indisponível:',errorText(e));return false}}
function showAppError(error,prefix='Não foi possível carregar os dados'){const message=errorText(error);console.error(prefix,error);setCloud(`${prefix}: ${message}`,'error');return message}
async function loadSchool(schoolId,{preserveActual=false}={}){
  if(!schoolId)return;
  state.ready=false;
  setCloud('Carregando dados...','saving');
  try{
    await ensureToken();
    const rows=await rest('school_data',`select=payload,updated_at&school_id=eq.${q(schoolId)}`);
    let payload=rows?.[0]?.payload;
    if(!payload){
      const school=state.schools.find(item=>item.id===schoolId)||state.preview?.school||{};
      payload=window.GFP_APP.createEmptyData(school);
      await rest('school_data','',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:{school_id:schoolId,payload}});
    }
    state.schoolId=schoolId;
    if(!preserveActual&&!state.preview)state.actualSchoolId=schoolId;
    state.role=state.profile.system_role==='master'?'master':(activeMembership(schoolId)?.role||'');
    cacheLocal('gfp_last_school',schoolId);
    cacheLocal(localCacheKey(),JSON.stringify(payload));
    applyUI();
    if(!window.GFP_APP||typeof window.GFP_APP.setData!=='function')throw new Error('A interface do aplicativo não terminou de iniciar. Atualize a página.');
    window.GFP_APP.setData(payload);
    state.ready=true;
    window.GFP_APP.refreshStorageInfo();
    setCloud('Dados sincronizados','ok');
    return payload;
  }catch(error){
    state.ready=false;
    if(state.schoolId)try{applyUI()}catch(uiError){console.error('Falha ao atualizar a interface:',uiError)}
    showAppError(error);
    throw error;
  }
}
async function ensureSchoolReady(){if(isReadOnly())throw new Error('Saia do modo somente leitura antes de alterar os dados.');if(state.schoolId&&state.ready)return state.schoolId;const selected=el('schoolSelector')?.value;if(!selected)throw new Error('Selecione uma unidade e aguarde a conexão antes de importar.');await loadSchool(selected);if(!state.schoolId||!state.ready)throw new Error('Não foi possível conectar a unidade selecionada ao banco.');return state.schoolId}
function queueSave(payload){try{localStorage.setItem(localCacheKey(),JSON.stringify(payload))}catch{}if(!state.ready||!state.schoolId||isReadOnly())return;state.pendingPayload=payload;clearTimeout(state.saveTimer);setCloud('Alterações pendentes...','saving');state.saveTimer=setTimeout(()=>flushPendingSave().catch(e=>console.error(e)),650)}
function payloadSummary(payload){return['employees','teachers','events','absences','occurrences'].map(k=>Array.isArray(payload?.[k])?payload[k].length:-1).join(':')}
async function flushPendingSave(){clearTimeout(state.saveTimer);if(state.savePromise)return state.savePromise;if(!state.pendingPayload||isReadOnly()||!state.schoolId)return;state.savePromise=(async()=>{while(state.pendingPayload){const payload=state.pendingPayload;state.pendingPayload=null;state.saving=true;setCloud('Salvando...','saving');try{await ensureToken();await rest('school_data','',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:{school_id:state.schoolId,payload,updated_by:state.user.id}});const confirmed=await rest('school_data',`select=payload,updated_at&school_id=eq.${q(state.schoolId)}`),stored=confirmed?.[0]?.payload;if(!stored||payloadSummary(stored)!==payloadSummary(payload))throw new Error('O banco não confirmou todos os dados enviados.');state.lastSaved=new Date().toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'});setCloud('Salvo e confirmado às '+state.lastSaved,'ok');await audit('save_school_data','school_data',{version:window.GFP_APP.version})}catch(e){state.pendingPayload=state.pendingPayload||payload;setCloud('Falha ao salvar — backup local preservado','error');throw e}finally{state.saving=false}}})().finally(()=>{state.savePromise=null});return state.savePromise}
async function saveNow(payload){await ensureSchoolReady();queueSave(payload);if(!state.pendingPayload)throw new Error('A unidade ainda não está pronta para salvar.');await flushPendingSave();window.GFP_APP.setData(payload)}
async function audit(action,entity,details={}){try{await rest('audit_logs','',{method:'POST',headers:{Prefer:'return=minimal'},body:{school_id:state.schoolId||null,actor_user_id:state.user.id,effective_user_id:state.preview?.user_id||state.user.id,action,entity,details}})}catch(e){console.warn('audit',e.message)}}
function canOpenView(view){const r=effectiveRole();if(view==='admin')return state.profile?.system_role==='master'&&!state.preview;if(r==='consulta')return['inicio','gerar','frequencia','relatorios','sobre'].includes(view);return true}
function isReadOnly(){return Boolean(state.preview)||effectiveRole()==='consulta'}
function applyUI(){const r=effectiveRole();document.body.classList.remove('role-master','role-admin','role-operator','role-consulta','preview-readonly');document.body.classList.add('role-'+r);if(isReadOnly())document.body.classList.add('preview-readonly');el('sessionUser').textContent=state.preview?.full_name||state.profile?.full_name||state.user?.email||'';el('sessionRole').textContent=roleLabel(r);const school=state.schools.find(s=>s.id===state.schoolId)||state.preview?.school;el('headerSchoolName').textContent=school?.short_name||school?.name||'Unidade não selecionada';el('previewAsBanner').classList.toggle('active',Boolean(state.preview));if(state.preview)el('previewAsText').textContent=`${state.preview.full_name} • ${school?.name||''} • ${roleLabel(r)} • somente leitura`;el('aboutContactText').textContent=[cfg.supportEmail&&cfg.supportEmail!=='SEU-EMAIL-DE-SUPORTE'?cfg.supportEmail:'',cfg.supportWhatsApp?('WhatsApp: '+cfg.supportWhatsApp):''].filter(Boolean).join(' • ')||'Contato de suporte não configurado.';document.querySelectorAll('nav button').forEach(b=>{if(b.dataset.view==='admin')b.style.display=(state.profile?.system_role==='master'&&!state.preview)?'':'none'});window.GFP_APP.refreshStorageInfo();window.GFP_APP.refreshDashboard?.()}
function populateSchoolSelector(){const s=el('schoolSelector');s.innerHTML=state.schools.map(x=>`<option value="${x.id}">${escapeHtml(x.name)}</option>`).join('');if(state.schoolId)s.value=state.schoolId;s.disabled=Boolean(state.preview)}
function escapeHtml(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function showApp(){el('authScreen').style.display='none';el('onlineApp').hidden=false;document.documentElement.classList.remove('auth-pending');populateSchoolSelector();applyUI();if(state.profile.system_role==='master')await refreshAdmin()}
function showAuthError(msg){const e=el('authError');e.textContent=msg;e.style.display='block'}
function retryRestoredStartup(){const key='gfp_restored_startup_retry_'+runtimeVersion;try{if(sessionStorage.getItem(key))return false;sessionStorage.setItem(key,'1')}catch{return false}setCloud('Atualizando a sessão salva...','saving');setTimeout(()=>location.reload(),80);return true}
function clearRestoredStartupRetry(){try{sessionStorage.removeItem('gfp_restored_startup_retry_'+runtimeVersion)}catch{}}
async function start(){document.documentElement.classList.add('auth-pending');if(recoveryFromUrl())return;if(!configured()){el('authSetup').style.display='block';return}if(restoreSession()){let appShown=false;try{await validateRestoredSession();await loadIdentity();const last=localStorage.getItem('gfp_last_school');const first=(last&&state.schools.some(s=>s.id===last))?last:state.schools[0]?.id;await showApp();appShown=true;if(first)await loadSchool(first);clearRestoredStartupRetry()}catch(e){console.error(e);if(appShown){if(!retryRestoredStartup())showAppError(e)}else{clearSession();showAuthError(errorText(e))}}}}
async function onLogin(e){e.preventDefault();el('authError').style.display='none';const fd=new FormData(e.target);const btn=e.target.querySelector('button');btn.disabled=true;btn.textContent='Entrando...';let appShown=false;try{await signIn(fd.get('email'),fd.get('password'));await loadIdentity();await showApp();appShown=true;const first=state.schools[0]?.id;if(first)await loadSchool(first);else if(state.profile.system_role==='master'){setCloud('Cadastre a primeira escola','');window.GFP_APP.showView('admin')}}catch(err){if(appShown)showAppError(err);else showAuthError(errorText(err))}finally{btn.disabled=false;btn.textContent='Entrar'}}
function schoolFormData(form){const fd=Object.fromEntries(new FormData(form).entries()),name=String(fd.name||'').trim(),shortName=String(fd.short_name||'').trim(),code=String(fd.code||'').trim();if(name.length<3)throw new Error('Informe o nome da unidade com pelo menos 3 caracteres.');if(shortName.length<2)throw new Error('Informe o nome curto com pelo menos 2 caracteres.');return{id:String(fd.id||''),name,short_name:shortName,code:code||null,active:fd.active!=='false'}}
function resetSchoolForm(){const form=el('schoolAdminForm');form.reset();form.elements.id.value='';el('schoolAdminTitle').textContent='Nova escola';el('schoolAdminSubmit').textContent='Cadastrar escola';el('schoolAdminCancel').hidden=true;el('schoolActiveField').hidden=true}
function editSchool(id){const school=state.adminSchools.find(s=>s.id===id);if(!school)return;const form=el('schoolAdminForm');form.elements.id.value=school.id;form.elements.name.value=school.name||'';form.elements.short_name.value=school.short_name||'';form.elements.code.value=school.code||'';form.querySelector(`input[name="active"][value="${school.active?'true':'false'}"]`).checked=true;el('schoolAdminTitle').textContent='Editar escola';el('schoolAdminSubmit').textContent='Salvar alterações';el('schoolAdminCancel').hidden=false;el('schoolActiveField').hidden=false;message('schoolAdminMessage','');form.scrollIntoView({behavior:'smooth',block:'start'});form.elements.name.focus()}
async function syncSchoolsAfterAdminChange(previousSchoolId=state.schoolId){await loadIdentity();populateSchoolSelector();await refreshAdmin();if(previousSchoolId&&!state.schools.some(s=>s.id===previousSchoolId)){const next=state.schools[0];state.schoolId='';state.actualSchoolId='';state.ready=false;if(next)await loadSchool(next.id);else{localStorage.removeItem('gfp_last_school');applyUI();window.GFP_APP.refreshStorageInfo();setCloud('Nenhuma escola ativa','')}}else{populateSchoolSelector();applyUI()}}
async function saveSchool(e){e.preventDefault();message('schoolAdminMessage','Salvando...');try{const school=schoolFormData(e.target),editing=Boolean(school.id),previousSchoolId=state.schoolId;if(editing){await rest('schools',`id=eq.${q(school.id)}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:{name:school.name,short_name:school.short_name,code:school.code,active:school.active}})}else{const rows=await rest('schools','',{method:'POST',headers:{Prefer:'return=representation'},body:{name:school.name,short_name:school.short_name,code:school.code,active:true}}),created=rows?.[0];if(!created)throw new Error('A escola foi criada, mas o servidor não retornou o cadastro. Atualize a página.');await rest('school_data','',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:{school_id:created.id,payload:window.GFP_APP.createEmptyData(created)}})}resetSchoolForm();await syncSchoolsAfterAdminChange(previousSchoolId);message('schoolAdminMessage',editing?'Escola atualizada com sucesso.':'Escola cadastrada vazia com sucesso.','ok')}catch(err){message('schoolAdminMessage',errorText(err),'error')}}
async function deleteSchool(id){const school=state.adminSchools.find(item=>item.id===id);if(!school)return;const typed=prompt(`Esta ação excluirá permanentemente a escola, todos os seus dados e vínculos.\n\nDigite o nome da unidade para confirmar:\n${school.name}`);if(typed===null)return;if(typed.trim()!==school.name.trim()){alert('O nome informado não corresponde à escola. Exclusão cancelada.');return}const previousSchoolId=state.schoolId;message('schoolAdminMessage','Excluindo escola...');try{if(id===state.schoolId){clearTimeout(state.saveTimer);state.pendingPayload=null;state.ready=false}const deleted=await rest('schools',`id=eq.${q(id)}&select=id`,{method:'DELETE',headers:{Prefer:'return=representation'}});if(!deleted?.length)throw new Error('A escola não foi excluída. Atualize a página e tente novamente.');try{localStorage.removeItem('gfp_school_cache_'+id)}catch{}resetSchoolForm();await syncSchoolsAfterAdminChange(previousSchoolId);message('schoolAdminMessage','Escola excluída permanentemente.','ok')}catch(error){message('schoolAdminMessage',errorText(error),'error')}}
async function adminCall(body){await ensureToken();return request('/functions/v1/admin-users',{method:'POST',body})}
function resetUserForm(){const form=el('userAdminForm');form.reset();form.elements.user_id.value='';form.elements.membership_id.value='';form.elements.password.required=true;el('userAdminTitle').textContent='Criar usuário';el('userAdminSubmit').textContent='Criar usuário';el('userAdminCancel').hidden=true;el('userPasswordHint').textContent='Obrigatória na criação.'}
function editUser(userId,membershipId){const user=state.adminUsers.find(item=>item.id===userId),membership=user?.memberships?.find(item=>item.id===membershipId);if(!user||user.system_role==='master')return;const form=el('userAdminForm');form.elements.user_id.value=user.id;form.elements.membership_id.value=membership?.id||'';form.elements.full_name.value=user.full_name||'';form.elements.email.value=user.email||'';form.elements.password.value='';form.elements.password.required=false;if(membership){form.elements.school_id.value=membership.school_id;form.elements.role.value=membership.role}form.querySelector(`input[name="active"][value="${user.active?'true':'false'}"]`).checked=true;el('userAdminTitle').textContent='Editar usuário';el('userAdminSubmit').textContent='Salvar alterações';el('userAdminCancel').hidden=false;el('userPasswordHint').textContent='Deixe em branco para manter a senha atual.';message('userAdminMessage','');form.scrollIntoView({behavior:'smooth',block:'start'});form.elements.full_name.focus()}
async function saveUser(e){e.preventDefault();const fd=Object.fromEntries(new FormData(e.target).entries()),editing=Boolean(fd.user_id);message('userAdminMessage',editing?'Salvando alterações...':'Criando usuário...');try{await adminCall({action:editing?'update_user_details':'create',...fd,active:fd.active==='true'});resetUserForm();await refreshAdmin();message('userAdminMessage',editing?'Usuário atualizado com sucesso.':'Usuário criado. Entregue a senha temporária e peça a troca no primeiro acesso.','ok')}catch(err){message('userAdminMessage',errorText(err),'error')}}
async function addMembership(e){e.preventDefault();const fd=Object.fromEntries(new FormData(e.target).entries());message('membershipAdminMessage','Salvando vínculo...');try{await adminCall({action:'add_membership',...fd});await refreshAdmin();message('membershipAdminMessage','Vínculo salvo com sucesso.','ok')}catch(err){message('membershipAdminMessage',errorText(err),'error')}}
async function deleteUser(userId){const user=state.adminUsers.find(item=>item.id===userId);if(!user||user.system_role==='master')return;const label=user.email||user.full_name,typed=prompt(`Esta ação excluirá permanentemente o login e todos os vínculos deste usuário.\n\nDigite o e-mail para confirmar:\n${label}`);if(typed===null)return;if(typed.trim().toLocaleLowerCase('pt-BR')!==String(label).trim().toLocaleLowerCase('pt-BR')){alert('O e-mail informado não corresponde ao usuário. Exclusão cancelada.');return}message('userAdminMessage','Excluindo usuário...');try{await adminCall({action:'delete_user',user_id:user.id});resetUserForm();await refreshAdmin();message('userAdminMessage','Usuário excluído permanentemente.','ok')}catch(error){message('userAdminMessage',errorText(error),'error')}}
function message(id,text,type=''){const x=el(id);x.textContent=errorText(text,type==='error'?'Não foi possível concluir a operação.':'');x.style.color=type==='error'?'#b42318':type==='ok'?'#157347':'#475467'}
async function refreshAdmin(){if(state.profile?.system_role!=='master'||state.preview)return;try{const result=await adminCall({action:'list'});state.adminUsers=result.users||[];state.adminSchools=result.schools||[];renderAdmin()}catch(e){message('userAdminMessage',errorText(e),'error')}}
function renderAdmin(){const schools=state.adminSchools,activeSchools=schools.filter(s=>s.active);el('adminUserSchool').innerHTML=activeSchools.map(s=>`<option value="${s.id}">${escapeHtml(s.name)}</option>`).join('');el('adminMembershipSchool').innerHTML=el('adminUserSchool').innerHTML;el('adminExistingUser').innerHTML=state.adminUsers.filter(u=>u.system_role!=='master').map(u=>`<option value="${u.id}">${escapeHtml(u.full_name||u.email)}</option>`).join('');el('adminSchoolsTable').innerHTML=schools.length?`<div class="table-wrap"><table class="admin-table"><thead><tr><th>Escola</th><th>Nome curto</th><th>Código</th><th>Status</th><th>Ações</th></tr></thead><tbody>${schools.map(s=>`<tr><td>${escapeHtml(s.name)}</td><td>${escapeHtml(s.short_name||'')}</td><td>${escapeHtml(s.code||'')}</td><td><span class="${s.active?'tag-active':'tag-inactive'}">${s.active?'Ativa':'Inativa'}</span></td><td><button class="mini-btn edit admin-school-edit" data-school="${s.id}" type="button">Editar</button> <button class="mini-btn del admin-school-delete" data-school="${s.id}" type="button">Excluir</button></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">Nenhuma escola.</div>';
const rows=[];for(const u of state.adminUsers){const memberships=u.memberships||[];if(!memberships.length)rows.push({u,m:null});else memberships.forEach(m=>rows.push({u,m}))}el('adminUsersTable').innerHTML=rows.length?`<div class="table-wrap"><table class="admin-table"><thead><tr><th>Usuário</th><th>Escola</th><th>Permissão</th><th>Status</th><th>Ações</th></tr></thead><tbody>${rows.map(({u,m})=>`<tr><td>${escapeHtml(u.full_name||u.email)}<br><small>${escapeHtml(u.email||'')}</small></td><td>${escapeHtml(m?.school?.name||'Sem vínculo')}</td><td>${m?escapeHtml(roleLabel(m.role)):escapeHtml(roleLabel(u.system_role))}</td><td><span class="${u.active?'tag-active':'tag-inactive'}">${u.active?'Ativo':'Inativo'}</span></td><td>${u.system_role!=='master'&&m?`<button class="mini-btn edit admin-user-edit" data-user="${u.id}" data-membership="${m.id}" type="button">Editar</button> <button class="mini-btn edit admin-preview" data-user="${u.id}" data-school="${m.school_id}" type="button">Visualizar</button> <button class="mini-btn edit admin-reset" data-user="${u.id}" type="button">Nova senha</button> <button class="mini-btn del admin-user-delete" data-user="${u.id}" type="button">Excluir</button>`:'Conta mestre protegida'}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">Nenhum usuário cadastrado.</div>';document.querySelectorAll('.admin-school-edit').forEach(b=>b.addEventListener('click',()=>editSchool(b.dataset.school)));document.querySelectorAll('.admin-school-delete').forEach(b=>b.addEventListener('click',()=>deleteSchool(b.dataset.school)));document.querySelectorAll('.admin-user-edit').forEach(b=>b.addEventListener('click',()=>editUser(b.dataset.user,b.dataset.membership)));document.querySelectorAll('.admin-user-delete').forEach(b=>b.addEventListener('click',()=>deleteUser(b.dataset.user)));document.querySelectorAll('.admin-preview').forEach(b=>b.addEventListener('click',()=>enterPreview(b.dataset.user,b.dataset.school)));document.querySelectorAll('.admin-reset').forEach(b=>b.addEventListener('click',()=>resetUserPassword(b.dataset.user)))}
async function resetUserPassword(userId){const password=prompt('Digite uma nova senha temporária com pelo menos 8 caracteres:');if(!password)return;if(password.length<8){alert('A senha precisa ter pelo menos 8 caracteres.');return}try{await adminCall({action:'reset_password',user_id:userId,password});alert('Senha temporária atualizada.')}catch(e){alert(errorText(e))}}
async function enterPreview(userId,schoolId){const u=state.adminUsers.find(x=>x.id===userId),m=u?.memberships?.find(x=>x.school_id===schoolId);if(!u||!m)return;state.preview={user_id:u.id,full_name:u.full_name||u.email,role:m.role,school:m.school};state.actualSchoolId=state.schoolId;state.schools=await rest('schools','select=*&active=eq.true&order=name.asc');populateSchoolSelector();await loadSchool(schoolId,{preserveActual:true});applyUI();window.GFP_APP.showView('inicio')}
async function exitPreview(){const back=state.actualSchoolId;state.preview=null;await loadIdentity();populateSchoolSelector();if(back&&state.schools.some(s=>s.id===back))await loadSchool(back);else if(state.schools[0])await loadSchool(state.schools[0].id);applyUI();await refreshAdmin()}
function blockPreviewMutations(e){if(!state.preview)return;const target=e.target;const form=target.closest?.('form');const view=target.closest?.('.view')?.id||'';if(e.type==='submit'&&form){e.preventDefault();e.stopImmediatePropagation();alert('O modo de visualização é somente leitura.');return}if(e.type==='click'&&(target.matches('.mini-btn.edit,.mini-btn.del,.btn.danger')||['view-config','view-funcionarios','view-professores','view-calendario','view-afastamentos','view-ocorrencias','view-backup'].includes(view)&&target.matches('button.btn'))){e.preventDefault();e.stopImmediatePropagation();alert('O modo de visualização é somente leitura.')}}
function bind(){el('loginForm').addEventListener('submit',onLogin);el('recoveryForm').addEventListener('submit',completeRecovery);el('forgotPasswordBtn').addEventListener('click',()=>resetPassword().catch(e=>showAuthError(errorText(e))));el('logoutBtn').addEventListener('click',signOut);el('schoolSelector').addEventListener('change',e=>loadSchool(e.target.value).catch(()=>{}));el('schoolAdminForm').addEventListener('submit',saveSchool);el('schoolAdminCancel').addEventListener('click',()=>{resetSchoolForm();message('schoolAdminMessage','')});el('userAdminForm').addEventListener('submit',saveUser);el('userAdminCancel').addEventListener('click',()=>{resetUserForm();message('userAdminMessage','')});el('membershipAdminForm').addEventListener('submit',addMembership);el('exitPreviewBtn').addEventListener('click',exitPreview);document.addEventListener('submit',blockPreviewMutations,true);document.addEventListener('click',blockPreviewMutations,true)}
bind();
window.gfpOnline={start,queueSave,saveNow,ensureSchoolReady,isReady:()=>state.ready,isReadOnly,canOpenView,storageLabel:()=>state.schoolId?'Banco online da unidade selecionada':'Nenhuma unidade selecionada',currentSchool:()=>state.schools.find(item=>item.id===state.schoolId)||state.preview?.school||null,refreshAdmin,dashboardContext:()=>{const school=state.schools.find(item=>item.id===state.schoolId)||state.preview?.school;return{userName:state.preview?.full_name||state.profile?.full_name||state.user?.email||'',schoolName:school?.name||school?.short_name||'',cloudStatus:el('cloudStatus')?.textContent||'',isMaster:state.profile?.system_role==='master'&&!state.preview,schoolCount:state.schools.length,userCount:state.adminUsers.filter(item=>item.system_role!=='master').length}}};
window.addEventListener('pageshow',event=>{if(event.persisted)location.reload()});
start();
})();
