(function(){
'use strict';
const cfg=window.GFP_CONFIG||{};
const state={accessToken:'',refreshToken:'',expiresAt:0,user:null,profile:null,memberships:[],schools:[],schoolId:'',actualSchoolId:'',role:'',preview:null,ready:false,saveTimer:null,saving:false,lastSaved:'',adminUsers:[]};
const configured=()=>/^https:\/\/[^.]+\.supabase\.co$/.test(String(cfg.supabaseUrl||''))&&!String(cfg.anonKey||'').includes('SUA-CHAVE');
const base=()=>String(cfg.supabaseUrl||'').replace(/\/$/,'');
const authKey='gfp_online_auth_v2';
function el(id){return document.getElementById(id)}
function jsonHeaders(auth=true){const h={'apikey':cfg.anonKey,'Content-Type':'application/json'};if(auth&&state.accessToken)h.Authorization='Bearer '+state.accessToken;return h}
async function request(path,{method='GET',body,headers={},auth=true}={}){const res=await fetch(base()+path,{method,headers:{...jsonHeaders(auth),...headers},body:body===undefined?undefined:JSON.stringify(body)});let payload=null;const text=await res.text();if(text)try{payload=JSON.parse(text)}catch{payload=text}if(!res.ok){const msg=payload?.msg||payload?.message||payload?.error_description||payload?.error||`Erro ${res.status}`;throw new Error(msg)}return payload}
function saveSession(){localStorage.setItem(authKey,JSON.stringify({accessToken:state.accessToken,refreshToken:state.refreshToken,expiresAt:state.expiresAt,user:state.user}))}
function clearSession(){localStorage.removeItem(authKey);state.accessToken='';state.refreshToken='';state.expiresAt=0;state.user=null}
function restoreSession(){try{const s=JSON.parse(localStorage.getItem(authKey)||'null');if(s){Object.assign(state,s);return true}}catch{}return false}
async function signIn(email,password){const x=await request('/auth/v1/token?grant_type=password',{method:'POST',body:{email,password},auth:false});state.accessToken=x.access_token;state.refreshToken=x.refresh_token;state.expiresAt=Date.now()+(Number(x.expires_in||3600)*1000);state.user=x.user;saveSession()}
async function refreshSession(){if(!state.refreshToken)throw new Error('Sessão expirada.');const x=await request('/auth/v1/token?grant_type=refresh_token',{method:'POST',body:{refresh_token:state.refreshToken},auth:false});state.accessToken=x.access_token;state.refreshToken=x.refresh_token||state.refreshToken;state.expiresAt=Date.now()+(Number(x.expires_in||3600)*1000);state.user=x.user||state.user;saveSession()}
async function ensureToken(){if(state.accessToken&&Date.now()<state.expiresAt-60000)return;if(state.refreshToken)await refreshSession();else throw new Error('Faça login novamente.')}
async function signOut(){try{await request('/auth/v1/logout',{method:'POST',body:{}})}catch{}clearSession();location.reload()}
async function resetPassword(){const email=prompt('Informe o e-mail da conta:');if(!email)return;await request('/auth/v1/recover?redirect_to='+encodeURIComponent(location.origin),{method:'POST',body:{email},auth:false});alert('Se o e-mail estiver cadastrado, o Supabase enviará as instruções de recuperação.')}
function q(v){return encodeURIComponent(v)}
async function rest(table,query='',opts={}){await ensureToken();return request(`/rest/v1/${table}${query?('?'+query):''}`,opts)}
function recoveryFromUrl(){const raw=(location.hash||'').replace(/^#/,'');if(!raw)return false;const hp=new URLSearchParams(raw);if(hp.get('type')!=='recovery'||!hp.get('access_token'))return false;state.accessToken=hp.get('access_token')||'';state.refreshToken=hp.get('refresh_token')||'';state.expiresAt=Date.now()+(Number(hp.get('expires_in')||3600)*1000);saveSession();el('loginForm').style.display='none';el('forgotPasswordBtn').style.display='none';el('recoveryForm').style.display='block';history.replaceState(null,'',location.pathname+location.search);return true}
async function completeRecovery(e){e.preventDefault();const fd=new FormData(e.target),password=String(fd.get('password')||''),confirm=String(fd.get('confirm')||'');if(password.length<8){showAuthError('A senha precisa ter pelo menos 8 caracteres.');return}if(password!==confirm){showAuthError('As senhas não coincidem.');return}try{await request('/auth/v1/user',{method:'PUT',body:{password}});alert('Senha atualizada. Entre novamente com a nova senha.');clearSession();location.reload()}catch(err){showAuthError(err.message)}}
async function loadIdentity(){const uid=state.user?.id;if(!uid)throw new Error('Usuário não identificado.');const profiles=await rest('profiles',`select=id,full_name,system_role,active&id=eq.${q(uid)}`);state.profile=profiles?.[0];if(!state.profile||!state.profile.active)throw new Error('Este usuário está inativo ou não possui perfil no sistema.');if(state.profile.system_role==='master'){
  state.schools=await rest('schools','select=*&active=eq.true&order=name.asc');
  state.memberships=[];state.role='master';
}else{
  state.memberships=await rest('memberships',`select=id,user_id,school_id,role,active,schools(id,name,short_name,code,active)&user_id=eq.${q(uid)}&active=eq.true`);
  state.schools=state.memberships.map(m=>m.schools).filter(Boolean).filter(s=>s.active);
}
if(!state.schools.length&&state.profile.system_role!=='master')throw new Error('Seu usuário não está vinculado a nenhuma escola ativa.');
}
function activeMembership(schoolId){if(state.profile?.system_role==='master')return{role:'master'};return state.memberships.find(m=>m.school_id===schoolId&&m.active)}
function effectiveRole(){return state.preview?.role||state.role||activeMembership(state.schoolId)?.role||''}
function roleLabel(r){return({master:'Administrador Geral',admin:'Administrador da escola',operator:'Operador',consulta:'Consulta'})[r]||r||'Sem permissão'}
function setCloud(text,cls=''){const e=el('cloudStatus');if(e){e.textContent=text;e.className='cloud-status '+cls}}
function localCacheKey(){return 'gfp_school_cache_'+(state.schoolId||'none')}
async function loadSchool(schoolId,{preserveActual=false}={}){if(!schoolId)return;await ensureToken();setCloud('Carregando dados...','saving');const rows=await rest('school_data',`select=payload,updated_at&school_id=eq.${q(schoolId)}`);let payload=rows?.[0]?.payload;if(!payload){payload=window.GFP_APP.createInitialData();await rest('school_data','',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:{school_id:schoolId,payload}})}state.schoolId=schoolId;if(!preserveActual&&!state.preview)state.actualSchoolId=schoolId;state.role=state.profile.system_role==='master'?'master':(activeMembership(schoolId)?.role||'');localStorage.setItem('gfp_last_school',schoolId);localStorage.setItem(localCacheKey(),JSON.stringify(payload));window.GFP_APP.setData(payload);applyUI();setCloud('Dados sincronizados','ok');state.ready=true}
function queueSave(payload){try{localStorage.setItem(localCacheKey(),JSON.stringify(payload))}catch{}if(!state.ready||!state.schoolId||isReadOnly())return;clearTimeout(state.saveTimer);setCloud('Alterações pendentes...','saving');state.saveTimer=setTimeout(()=>savePayload(payload),650)}
async function savePayload(payload){if(state.saving||isReadOnly()||!state.schoolId)return;state.saving=true;setCloud('Salvando...','saving');try{await ensureToken();await rest('school_data','',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:{school_id:state.schoolId,payload,updated_by:state.user.id}});state.lastSaved=new Date().toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'});setCloud('Salvo às '+state.lastSaved,'ok');await audit('save_school_data','school_data',{version:window.GFP_APP.version})}catch(e){console.error(e);setCloud('Falha ao salvar — backup local preservado','error')}finally{state.saving=false}}
async function audit(action,entity,details={}){try{await rest('audit_logs','',{method:'POST',headers:{Prefer:'return=minimal'},body:{school_id:state.schoolId||null,actor_user_id:state.user.id,effective_user_id:state.preview?.user_id||state.user.id,action,entity,details}})}catch(e){console.warn('audit',e.message)}}
function canOpenView(view){const r=effectiveRole();if(view==='admin')return state.profile?.system_role==='master'&&!state.preview;if(r==='consulta')return['inicio','gerar','frequencia','relatorios','sobre'].includes(view);return true}
function isReadOnly(){return Boolean(state.preview)||effectiveRole()==='consulta'}
function applyUI(){const r=effectiveRole();document.body.classList.remove('role-master','role-admin','role-operator','role-consulta','preview-readonly');document.body.classList.add('role-'+r);if(isReadOnly())document.body.classList.add('preview-readonly');el('sessionUser').textContent=state.preview?.full_name||state.profile?.full_name||state.user?.email||'';el('sessionRole').textContent=roleLabel(r);const school=state.schools.find(s=>s.id===state.schoolId)||state.preview?.school;el('headerSchoolName').textContent=school?.short_name||school?.name||'Unidade não selecionada';el('previewAsBanner').classList.toggle('active',Boolean(state.preview));if(state.preview)el('previewAsText').textContent=`${state.preview.full_name} • ${school?.name||''} • ${roleLabel(r)} • somente leitura`;el('aboutContactText').textContent=[cfg.supportEmail&&cfg.supportEmail!=='SEU-EMAIL-DE-SUPORTE'?cfg.supportEmail:'',cfg.supportWhatsApp?('WhatsApp: '+cfg.supportWhatsApp):''].filter(Boolean).join(' • ')||'Contato de suporte não configurado.';document.querySelectorAll('nav button').forEach(b=>{if(b.dataset.view==='admin')b.style.display=(state.profile?.system_role==='master'&&!state.preview)?'':'none'});window.GFP_APP.refreshStorageInfo()}
function populateSchoolSelector(){const s=el('schoolSelector');s.innerHTML=state.schools.map(x=>`<option value="${x.id}">${escapeHtml(x.name)}</option>`).join('');if(state.schoolId)s.value=state.schoolId;s.disabled=Boolean(state.preview)}
function escapeHtml(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function showApp(){el('authScreen').style.display='none';el('onlineApp').hidden=false;document.documentElement.classList.remove('auth-pending');populateSchoolSelector();applyUI();if(state.profile.system_role==='master')await refreshAdmin()}
function showAuthError(msg){const e=el('authError');e.textContent=msg;e.style.display='block'}
async function start(){document.documentElement.classList.add('auth-pending');if(recoveryFromUrl())return;if(!configured()){el('authSetup').style.display='block';return}if(restoreSession()){try{await ensureToken();await loadIdentity();const last=localStorage.getItem('gfp_last_school');const first=(last&&state.schools.some(s=>s.id===last))?last:state.schools[0]?.id;await showApp();if(first)await loadSchool(first)}catch(e){console.error(e);clearSession();showAuthError(e.message)}}}
async function onLogin(e){e.preventDefault();el('authError').style.display='none';const fd=new FormData(e.target);const btn=e.target.querySelector('button');btn.disabled=true;btn.textContent='Entrando...';try{await signIn(fd.get('email'),fd.get('password'));await loadIdentity();await showApp();const first=state.schools[0]?.id;if(first)await loadSchool(first);else if(state.profile.system_role==='master'){setCloud('Cadastre a primeira escola','');window.GFP_APP.showView('admin')}}catch(err){showAuthError(err.message)}finally{btn.disabled=false;btn.textContent='Entrar'}}
async function createSchool(e){e.preventDefault();const fd=Object.fromEntries(new FormData(e.target).entries());message('schoolAdminMessage','Salvando...');try{const rows=await rest('schools','',{method:'POST',headers:{Prefer:'return=representation'},body:{name:fd.name,short_name:fd.short_name||fd.name,code:fd.code||null,active:true}});const school=rows[0];await rest('school_data','',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:{school_id:school.id,payload:window.GFP_APP.createInitialData()}});e.target.reset();await loadIdentity();populateSchoolSelector();await refreshAdmin();message('schoolAdminMessage','Escola cadastrada com sucesso.','ok')}catch(err){message('schoolAdminMessage',err.message,'error')}}
async function adminCall(body){await ensureToken();return request('/functions/v1/admin-users',{method:'POST',body})}
async function createUser(e){e.preventDefault();const fd=Object.fromEntries(new FormData(e.target).entries());message('userAdminMessage','Criando usuário...');try{await adminCall({action:'create',...fd,active:fd.active==='true'});e.target.reset();await refreshAdmin();message('userAdminMessage','Usuário criado. Entregue a senha temporária e peça a troca no primeiro acesso.','ok')}catch(err){message('userAdminMessage',err.message,'error')}}
async function addMembership(e){e.preventDefault();const fd=Object.fromEntries(new FormData(e.target).entries());message('membershipAdminMessage','Salvando vínculo...');try{await adminCall({action:'add_membership',...fd});await refreshAdmin();message('membershipAdminMessage','Vínculo salvo com sucesso.','ok')}catch(err){message('membershipAdminMessage',err.message,'error')}}
async function updateUserMembership(userId,membershipId){const role=el('role_'+membershipId)?.value,active=el('active_'+userId)?.value==='true';try{await adminCall({action:'update_user',user_id:userId,membership_id:membershipId,role,active});await refreshAdmin();alert('Usuário atualizado.')}catch(e){alert(e.message)}}
function message(id,text,type=''){const x=el(id);x.textContent=text;x.style.color=type==='error'?'#b42318':type==='ok'?'#157347':'#475467'}
async function refreshAdmin(){if(state.profile?.system_role!=='master'||state.preview)return;try{const result=await adminCall({action:'list'});state.adminUsers=result.users||[];state.schools=result.schools||state.schools;populateSchoolSelector();renderAdmin()}catch(e){message('userAdminMessage',e.message,'error')}}
function renderAdmin(){const schools=state.schools;el('adminUserSchool').innerHTML=schools.map(s=>`<option value="${s.id}">${escapeHtml(s.name)}</option>`).join('');el('adminMembershipSchool').innerHTML=el('adminUserSchool').innerHTML;el('adminExistingUser').innerHTML=state.adminUsers.filter(u=>u.system_role!=='master').map(u=>`<option value="${u.id}">${escapeHtml(u.full_name||u.email)}</option>`).join('');el('adminSchoolsTable').innerHTML=schools.length?`<div class="table-wrap"><table class="admin-table"><thead><tr><th>Escola</th><th>Código</th><th>Status</th></tr></thead><tbody>${schools.map(s=>`<tr><td>${escapeHtml(s.name)}</td><td>${escapeHtml(s.code||'')}</td><td>${s.active?'Ativa':'Inativa'}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">Nenhuma escola.</div>';
const rows=[];for(const u of state.adminUsers){const memberships=u.memberships||[];if(!memberships.length)rows.push({u,m:null});else memberships.forEach(m=>rows.push({u,m}))}el('adminUsersTable').innerHTML=rows.length?`<div class="table-wrap"><table class="admin-table"><thead><tr><th>Usuário</th><th>Escola</th><th>Permissão</th><th>Status</th><th>Ações</th></tr></thead><tbody>${rows.map(({u,m})=>`<tr><td>${escapeHtml(u.full_name||u.email)}<br><small>${escapeHtml(u.email||'')}</small></td><td>${escapeHtml(m?.school?.name||'Sem vínculo')}</td><td>${m?`<select id="role_${m.id}" style="min-width:112px"><option value="admin" ${m.role==='admin'?'selected':''}>Administrador</option><option value="operator" ${m.role==='operator'?'selected':''}>Operador</option><option value="consulta" ${m.role==='consulta'?'selected':''}>Consulta</option></select>`:escapeHtml(roleLabel(u.system_role))}</td><td><select id="active_${u.id}" style="min-width:82px"><option value="true" ${u.active?'selected':''}>Ativo</option><option value="false" ${!u.active?'selected':''}>Inativo</option></select></td><td>${m?`<button class="mini-btn edit admin-save" data-user="${u.id}" data-membership="${m.id}" type="button">Salvar</button> <button class="mini-btn edit admin-preview" data-user="${u.id}" data-school="${m.school_id}" type="button">Visualizar</button> <button class="mini-btn edit admin-reset" data-user="${u.id}" type="button">Nova senha</button>`:''}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">Nenhum usuário cadastrado.</div>';document.querySelectorAll('.admin-save').forEach(b=>b.addEventListener('click',()=>updateUserMembership(b.dataset.user,b.dataset.membership)));document.querySelectorAll('.admin-preview').forEach(b=>b.addEventListener('click',()=>enterPreview(b.dataset.user,b.dataset.school)));document.querySelectorAll('.admin-reset').forEach(b=>b.addEventListener('click',()=>resetUserPassword(b.dataset.user)))}
async function resetUserPassword(userId){const password=prompt('Digite uma nova senha temporária com pelo menos 8 caracteres:');if(!password)return;if(password.length<8){alert('A senha precisa ter pelo menos 8 caracteres.');return}try{await adminCall({action:'reset_password',user_id:userId,password});alert('Senha temporária atualizada.')}catch(e){alert(e.message)}}
async function enterPreview(userId,schoolId){const u=state.adminUsers.find(x=>x.id===userId),m=u?.memberships?.find(x=>x.school_id===schoolId);if(!u||!m)return;state.preview={user_id:u.id,full_name:u.full_name||u.email,role:m.role,school:m.school};state.actualSchoolId=state.schoolId;state.schools=await rest('schools','select=*&active=eq.true&order=name.asc');populateSchoolSelector();await loadSchool(schoolId,{preserveActual:true});applyUI();window.GFP_APP.showView('inicio')}
async function exitPreview(){const back=state.actualSchoolId;state.preview=null;await loadIdentity();populateSchoolSelector();if(back&&state.schools.some(s=>s.id===back))await loadSchool(back);else if(state.schools[0])await loadSchool(state.schools[0].id);applyUI();await refreshAdmin()}
function blockPreviewMutations(e){if(!state.preview)return;const target=e.target;const form=target.closest?.('form');const view=target.closest?.('.view')?.id||'';if(e.type==='submit'&&form){e.preventDefault();e.stopImmediatePropagation();alert('O modo de visualização é somente leitura.');return}if(e.type==='click'&&(target.matches('.mini-btn.edit,.mini-btn.del,.btn.danger')||['view-config','view-funcionarios','view-professores','view-calendario','view-afastamentos','view-ocorrencias','view-backup'].includes(view)&&target.matches('button.btn'))){e.preventDefault();e.stopImmediatePropagation();alert('O modo de visualização é somente leitura.')}}
function bind(){el('loginForm').addEventListener('submit',onLogin);el('recoveryForm').addEventListener('submit',completeRecovery);el('forgotPasswordBtn').addEventListener('click',()=>resetPassword().catch(e=>showAuthError(e.message)));el('logoutBtn').addEventListener('click',signOut);el('schoolSelector').addEventListener('change',e=>loadSchool(e.target.value));el('schoolAdminForm').addEventListener('submit',createSchool);el('userAdminForm').addEventListener('submit',createUser);el('membershipAdminForm').addEventListener('submit',addMembership);el('exitPreviewBtn').addEventListener('click',exitPreview);document.addEventListener('submit',blockPreviewMutations,true);document.addEventListener('click',blockPreviewMutations,true)}
bind();
window.gfpOnline={start,queueSave,isReady:()=>state.ready,isReadOnly,canOpenView,storageLabel:()=>state.schoolId?'Banco online da unidade selecionada':'Nenhuma unidade selecionada',refreshAdmin};
start();
})();
