-- Gestão de Funcionários e Ponto 2.0 Online
-- Execute todo este arquivo no SQL Editor de um projeto Supabase novo.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null default '',
  system_role text not null default 'user' check (system_role in ('master','user')),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.schools (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  short_name text not null default '',
  code text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.memberships (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  school_id uuid not null references public.schools(id) on delete cascade,
  role text not null check (role in ('admin','operator','consulta')),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  unique(user_id, school_id)
);

create table if not exists public.school_data (
  school_id uuid primary key references public.schools(id) on delete cascade,
  payload jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id)
);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  school_id uuid references public.schools(id) on delete set null,
  actor_user_id uuid not null references auth.users(id) on delete restrict,
  effective_user_id uuid references auth.users(id) on delete set null,
  action text not null,
  entity text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create or replace function public.touch_updated_at() returns trigger language plpgsql as $$
begin new.updated_at=now(); return new; end; $$;

drop trigger if exists profiles_touch on public.profiles;
create trigger profiles_touch before update on public.profiles for each row execute function public.touch_updated_at();
drop trigger if exists schools_touch on public.schools;
create trigger schools_touch before update on public.schools for each row execute function public.touch_updated_at();
drop trigger if exists school_data_touch on public.school_data;
create trigger school_data_touch before update on public.school_data for each row execute function public.touch_updated_at();

create or replace function public.is_system_master()
returns boolean language sql stable security definer set search_path=public as $$
  select exists(select 1 from public.profiles p where p.id=auth.uid() and p.system_role='master' and p.active=true)
$$;

create or replace function public.has_school_role(target_school uuid, allowed_roles text[] default array['admin','operator','consulta'])
returns boolean language sql stable security definer set search_path=public as $$
  select public.is_system_master() or exists(
    select 1 from public.memberships m join public.profiles p on p.id=m.user_id
    where m.user_id=auth.uid() and m.school_id=target_school and m.active=true and p.active=true and m.role=any(allowed_roles)
  )
$$;

alter table public.profiles enable row level security;
alter table public.schools enable row level security;
alter table public.memberships enable row level security;
alter table public.school_data enable row level security;
alter table public.audit_logs enable row level security;

-- Recriação idempotente das políticas
do $$ declare r record; begin
  for r in select schemaname,tablename,policyname from pg_policies where schemaname='public' and tablename in ('profiles','schools','memberships','school_data','audit_logs') loop
    execute format('drop policy if exists %I on %I.%I',r.policyname,r.schemaname,r.tablename);
  end loop;
end $$;

create policy profiles_select on public.profiles for select to authenticated using (id=auth.uid() or public.is_system_master());
create policy profiles_master_all on public.profiles for all to authenticated using (public.is_system_master()) with check (public.is_system_master());

create policy schools_select on public.schools for select to authenticated using (public.has_school_role(id));
create policy schools_master_all on public.schools for all to authenticated using (public.is_system_master()) with check (public.is_system_master());

create policy memberships_select on public.memberships for select to authenticated using (user_id=auth.uid() or public.is_system_master());
create policy memberships_master_all on public.memberships for all to authenticated using (public.is_system_master()) with check (public.is_system_master());

create policy school_data_select on public.school_data for select to authenticated using (public.has_school_role(school_id));
create policy school_data_insert on public.school_data for insert to authenticated with check (public.has_school_role(school_id,array['admin','operator']));
create policy school_data_update on public.school_data for update to authenticated using (public.has_school_role(school_id,array['admin','operator'])) with check (public.has_school_role(school_id,array['admin','operator']));
create policy school_data_delete on public.school_data for delete to authenticated using (public.is_system_master());

create policy audit_insert on public.audit_logs for insert to authenticated with check (actor_user_id=auth.uid() and (school_id is null or public.has_school_role(school_id)));
create policy audit_select on public.audit_logs for select to authenticated using (public.is_system_master() or public.has_school_role(school_id,array['admin']));

revoke all on function public.is_system_master() from public;
revoke all on function public.has_school_role(uuid,text[]) from public;
grant execute on function public.is_system_master() to authenticated;
grant execute on function public.has_school_role(uuid,text[]) to authenticated;

grant select,insert,update,delete on public.profiles,public.schools,public.memberships,public.school_data,public.audit_logs to authenticated;
grant usage,select on sequence public.audit_logs_id_seq to authenticated;

-- Depois de criar manualmente o primeiro usuário no painel Auth, execute:
-- insert into public.profiles(id,full_name,system_role,active)
-- select id,'Sergio H. R. Braindib','master',true from auth.users where email='SEU-EMAIL';
