/* Banco de horas da unidade */
(function(){
function todayKey(){return new Date().toISOString().slice(0,10)}
function parseTimeBankHours(value){const text=String(value||'').trim().toLocaleLowerCase('pt-BR').replace(/\s+/g,'');if(!text)return 0;const time=text.replace('h',':').match(/^([+-]?\d+):([0-5]?\d)$/);if(time){const h=Number(time[1]),m=Number(time[2]);return Number.isFinite(h)&&Number.isFinite(m)?h+(h<0?-m/60:m/60):0}const n=Number(text.replace(',','.'));return Number.isFinite(n)?n:0}
function canonicalTimeBankEntry(o){const raw=parseTimeBankHours(o.hours),negative=o.operation==='subtract'||raw<0;return{id:o.id||uid(),personType:o.personType==='teacher'?'teacher':'employee',personId:o.personId||'',date:o.date||todayKey(),hours:Number((negative?-Math.abs(raw):Math.abs(raw)).toFixed(2)),note:String(o.note||o.observacao||o.motivo||'').trim(),createdAt:o.createdAt||new Date().toISOString()}}
const baseNormalizeDataTimeBank=normalizeData;
normalizeData=function(obj){const x=baseNormalizeDataTimeBank(obj);x.timeBank=Array.isArray(x.timeBank)?x.timeBank.filter(v=>v&&v.personType&&v.personId).map(canonicalTimeBankEntry).filter(v=>v.personId&&v.date&&v.hours!==0):[];x.timeBank.sort((a,b)=>(b.date||'').localeCompare(a.date||'')||nameCollator.compare(serverName(a.personType,a.personId),serverName(b.personType,b.personId)));return x};
data=normalizeData(data);persistDataOnly(data);

function canEditTimeBank(){return !window.gfpOnline?.isReadOnly?.()}
function timeBankPerson(type,id){const list=type==='teacher'?data.teachers:data.employees,item=list.find(p=>p.id===id);return item?{...item,_type:type,_key:`${type}:${id}`}:null}
function foldTimeBankText(value){return String(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLocaleLowerCase('pt-BR')}
function timeBankAllPeople(source='all'){const withEntries=new Set((data.timeBank||[]).map(e=>`${e.personType}:${e.personId}`));return[...data.employees.map(p=>({...p,_type:'employee',_key:`employee:${p.id}`})),...data.teachers.map(p=>({...p,_type:'teacher',_key:`teacher:${p.id}`}))].filter(p=>(source==='all'||p._type===source)&&(isActive(p)||withEntries.has(p._key))).sort((a,b)=>compareNames(a,b)||a._type.localeCompare(b._type))}
function timeBankSelectedYear(){return document.getElementById('timeBankYearFilter')?.value||String(new Date().getFullYear())}
function timeBankSearchValue(){return foldTimeBankText(document.getElementById('timeBankSearch')?.value||'')}
function timeBankEntryYears(){const current=String(new Date().getFullYear()),years=[...new Set([current,...(data.timeBank||[]).map(e=>(e.date||'').slice(0,4)).filter(Boolean)])];return years.sort((a,b)=>b.localeCompare(a))}
function renderTimeBankYearOptions(){const select=document.getElementById('timeBankYearFilter');if(!select)return;const current=select.value||String(new Date().getFullYear()),years=timeBankEntryYears();select.innerHTML=years.map(y=>`<option value="${y}">${y}</option>`).join('');select.value=years.includes(current)?current:years[0]}
function timeBankEntriesFor(type,id,year=timeBankSelectedYear()){return(data.timeBank||[]).filter(e=>e.personType===type&&e.personId===id&&(!year||(e.date||'').slice(0,4)===year)).sort((a,b)=>(b.date||'').localeCompare(a.date||''))}
function timeBankPeople(source='all',useSearch=true){const year=timeBankSelectedYear(),search=useSearch?timeBankSearchValue():'';return timeBankAllPeople(source).filter(p=>timeBankEntriesFor(p._type,p.id,year).length&&(search?foldTimeBankText(p.nome).includes(search):true))}
function timeBankTotal(type,id){return timeBankEntriesFor(type,id).reduce((sum,e)=>sum+Number(e.hours||0),0)}
function timeBankDayHours(type){return type==='teacher'?5:8}
function formatBankHours(value){const sign=value<0?'-':'';let minutes=Math.round(Math.abs(value)*60),h=Math.floor(minutes/60),m=minutes%60;return`${sign}${h}h${m?String(m).padStart(2,'0'):''}`}
function formatBankInput(value){let minutes=Math.round(Math.abs(value)*60),h=Math.floor(minutes/60),m=minutes%60;return`${h}:${String(m).padStart(2,'0')}`}
function formatBankEquivalent(value,type){const sign=value<0?'-':'';let minutes=Math.round(Math.abs(value)*60),dayMinutes=timeBankDayHours(type)*60,days=Math.floor(minutes/dayMinutes),rem=minutes%dayMinutes,h=Math.floor(rem/60),m=rem%60;return`${sign}${days} dia${days===1?'':'s'} e ${h}h${m?String(m).padStart(2,'0'):''}`}
function timeBankTypeLabel(type){return type==='teacher'?'Professor':'Funcionário'}
function timeBankRoleLabel(p){return String(p?._type==='teacher'?(p.disciplina||p.categoria||p.cargo||'Professor'):(p.cargo||p.situacaoFuncional||'Funcionário')).trim()}
function timeBankOptionLabel(p){const mat=p.matricula?` • Matr. ${p.matricula}`:'';return`${p.nome} - ${timeBankRoleLabel(p)}${mat}${isActive(p)?'':' - INATIVO'}`}
function resolveTimeBankPersonFromText(value){const text=foldTimeBankText(value);if(!text)return null;const people=timeBankAllPeople('all'),exact=people.find(p=>foldTimeBankText(timeBankOptionLabel(p))===text);if(exact)return exact;const matches=people.filter(p=>foldTimeBankText(p.nome).includes(text)||foldTimeBankText(timeBankOptionLabel(p)).includes(text));return matches.length===1?matches[0]:null}
function syncTimeBankPersonKey(){const form=document.getElementById('timeBankForm'),input=document.getElementById('timeBankPersonSearch');if(!form||!input)return;const person=resolveTimeBankPersonFromText(input.value);form.elements.personKey.value=person?person._key:''}
function setTimeBankPersonField(key){const form=document.getElementById('timeBankForm'),input=document.getElementById('timeBankPersonSearch');if(!form||!input)return;const person=timeBankAllPeople('all').find(p=>p._key===key);form.elements.personKey.value=person?person._key:'';input.value=person?timeBankOptionLabel(person):''}
function renderTimeBankOptions(){renderTimeBankYearOptions();const list=document.getElementById('timeBankPersonList'),form=document.getElementById('timeBankForm'),current=form?.elements?.personKey?.value||'';if(list){const people=timeBankAllPeople('all');list.innerHTML=people.map(p=>`<option value="${esc(timeBankOptionLabel(p))}"></option>`).join('');if(current)setTimeBankPersonField(current);else syncTimeBankPersonKey()}renderTimeBankReportPeople()}
function renderTimeBankReportPeople(){const source=document.getElementById('timeBankReportSource')?.value||'all',select=document.getElementById('timeBankReportPerson');if(!select)return;const current=select.value,people=timeBankPeople(source,false);select.innerHTML='<option value="all">Todos do filtro</option>'+people.map(p=>`<option value="${p._key}">${esc(p.nome)} - ${esc(timeBankRoleLabel(p))}</option>`).join('');select.value=[...select.options].some(o=>o.value===current)?current:'all'}
function initializeTimeBankForm(){const form=document.getElementById('timeBankForm'),issue=document.getElementById('timeBankIssueDate');if(form&&!form.elements.date.value)form.elements.date.value=todayKey();if(issue&&!issue.value)issue.value=todayKey()}
function renderTimeBankSummary(){const host=document.getElementById('timeBankTable');if(!host)return;const year=timeBankSelectedYear(),people=timeBankPeople('all'),totalBox=document.getElementById('timeBankGrandTotal');if(totalBox)totalBox.textContent=`${people.length} servidor${people.length===1?'':'es'} com lançamento em ${year}`;if(!people.length){host.innerHTML='<div class="empty">Nenhum lançamento encontrado para o ano e nome informados.</div>';return}host.innerHTML=`<div class="table-wrap"><table class="data"><thead><tr><th>Nome</th><th>Cargo/Função</th><th>Matrícula</th><th>Total</th><th>Equivalência</th><th>Lançamentos</th><th>Ação</th></tr></thead><tbody>${people.map(p=>{const total=timeBankTotal(p._type,p.id),count=timeBankEntriesFor(p._type,p.id).length,cls=total<0?'negative':total>0?'positive':'';return`<tr class="timebank-row" onclick="openTimeBankExtract('${p._type}','${p.id}')"><td>${esc(p.nome)}</td><td>${esc(timeBankRoleLabel(p))}</td><td>${esc(p.matricula||'')}</td><td class="timebank-balance ${cls}">${formatBankHours(total)}</td><td>${formatBankEquivalent(total,p._type)}</td><td>${count}</td><td><button class="mini-btn edit" type="button" onclick="event.stopPropagation();openTimeBankExtract('${p._type}','${p.id}')">Extrato</button></td></tr>`}).join('')}</tbody></table></div>`}
function resetTimeBankForm(){const form=document.getElementById('timeBankForm'),input=document.getElementById('timeBankPersonSearch');if(!form)return;form.reset();form.elements.id.value='';form.elements.personKey.value='';if(input)input.value='';form.elements.operation.value='add';form.elements.date.value=todayKey()}
const baseResetFormTimeBank=resetForm;
resetForm=function(id){baseResetFormTimeBank(id);if(id==='timeBankForm')resetTimeBankForm()};
function saveTimeBankEntry(event){event.preventDefault();if(!canEditTimeBank()){alert('O modo atual é somente leitura.');return}syncTimeBankPersonKey();const form=event.currentTarget,o=formObj(form);if(!o.personKey){alert('Digite o nome e selecione um funcionário ou professor da lista.');return}if(!o.date){alert('Informe a data do lançamento.');return}if(!(parseTimeBankHours(o.hours)>0)){alert('Informe a quantidade no formato horas:minutos. Ex.: 1:30.');return}const action=o.id?'update':'create',[personType,personId]=o.personKey.split(':'),item=canonicalTimeBankEntry({...o,personType,personId,id:o.id||uid()});if(o.id&&data.timeBank.some(x=>x.id===o.id))Object.assign(data.timeBank.find(x=>x.id===o.id),item);else data.timeBank.push(item);saveData();window.DIB_AUDIT?.record(action,'timebank',item.id);const yearSelect=document.getElementById('timeBankYearFilter');if(yearSelect){renderTimeBankYearOptions();yearSelect.value=(item.date||todayKey()).slice(0,4);renderTimeBankSummary();renderTimeBankReportPeople()}resetTimeBankForm()}
function openTimeBankExtract(type,id){const person=timeBankPerson(type,id);if(!person)return;const dialog=document.getElementById('timeBankExtractDialog'),content=document.getElementById('timeBankExtractContent'),title=document.getElementById('timeBankExtractTitle'),summary=document.getElementById('timeBankExtractSummary'),entries=timeBankEntriesFor(type,id),total=timeBankTotal(type,id),canEdit=canEditTimeBank();title.textContent=`Extrato — ${person.nome}`;summary.textContent=`${timeBankRoleLabel(person)} • ${entries.length} lançamento${entries.length===1?'':'s'} • 1 dia equivale a ${timeBankDayHours(type)}h`;content.innerHTML=`<div class="timebank-extract-summary"><div class="timebank-extract-card"><strong>${formatBankHours(total)}</strong><span>Total de horas</span></div><div class="timebank-extract-card"><strong>${formatBankEquivalent(total,type)}</strong><span>Equivalência</span></div><div class="timebank-extract-card"><strong>${entries.length}</strong><span>Lançamentos</span></div></div>${entries.length?`<div class="table-wrap"><table class="data"><thead><tr><th>Data</th><th>Lançamento</th><th>Motivo</th><th>Ações</th></tr></thead><tbody>${entries.map(e=>`<tr><td>${formatDatePt(e.date)}</td><td class="timebank-balance ${e.hours<0?'negative':'positive'}">${e.hours<0?'Subtrai ':'Soma '}${formatBankHours(Math.abs(e.hours))}</td><td>${esc(e.note||'')}</td><td>${canEdit?`<button class="mini-btn edit" type="button" onclick="editTimeBankEntry('${e.id}')">Editar</button> <button class="mini-btn del" type="button" onclick="deleteTimeBankEntry('${e.id}')">Excluir</button>`:''}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">Nenhum lançamento para este servidor.</div>'}`;dialog?.showModal()}
function closeTimeBankExtract(){document.getElementById('timeBankExtractDialog')?.close()}
function editTimeBankEntry(id){if(!canEditTimeBank())return;const e=(data.timeBank||[]).find(x=>x.id===id),form=document.getElementById('timeBankForm');if(!e||!form)return;closeTimeBankExtract();showView('banco-horas');form.elements.id.value=e.id;setTimeBankPersonField(`${e.personType}:${e.personId}`);form.elements.date.value=e.date||todayKey();form.elements.operation.value=e.hours<0?'subtract':'add';form.elements.hours.value=formatBankInput(e.hours);form.elements.note.value=e.note||'';form.scrollIntoView({behavior:'smooth',block:'center'})}
async function deleteTimeBankEntry(id){if(!canEditTimeBank())return;const entry=(data.timeBank||[]).find(e=>e.id===id);if(!entry)return;closeTimeBankExtract();const ok=await(window.GFP_APP?.confirmAction?window.GFP_APP.confirmAction({title:'Excluir lançamento?',message:'Este lançamento será removido do banco de horas.',confirmLabel:'Excluir',danger:true}):Promise.resolve(confirm('Excluir este lançamento?')));if(!ok){openTimeBankExtract(entry.personType,entry.personId);return}data.timeBank=(data.timeBank||[]).filter(e=>e.id!==id);saveData();window.DIB_AUDIT?.record('delete','timebank',id)}
function selectedReportPeople(){const source=document.getElementById('timeBankReportSource')?.value||'all',key=document.getElementById('timeBankReportPerson')?.value||'all';let people=timeBankPeople(source,false);if(key!=='all')people=people.filter(p=>p._key===key);return people}
function timeBankSimpleRows(people){return people.map(p=>{const total=timeBankTotal(p._type,p.id);return`<tr><td>${esc(p.nome)}</td><td>${esc(timeBankRoleLabel(p))}</td><td class="center">${esc(p.matricula||'')}</td><td class="center">${formatBankHours(total)}</td><td class="center">${formatBankEquivalent(total,p._type)}</td></tr>`}).join('')}
function timeBankDetailedBody(person){const entries=timeBankEntriesFor(person._type,person.id),total=timeBankTotal(person._type,person.id);return`<div class="extract-title">${esc(person.nome)} — ${esc(timeBankRoleLabel(person))}</div><div class="balance-line"><strong>Total:</strong> ${formatBankHours(total)} (${formatBankEquivalent(total,person._type)})</div>${entries.length?`<table class="report-table"><thead><tr><th>Data</th><th>Operação</th><th>Horas</th><th>Motivo</th></tr></thead><tbody>${entries.map(e=>`<tr><td class="center">${formatDatePt(e.date)}</td><td class="center">${e.hours<0?'Subtrair':'Somar'}</td><td class="center">${formatBankHours(Math.abs(e.hours))}</td><td>${esc(e.note||'')}</td></tr>`).join('')}</tbody></table>`:'<div class="report-empty">Sem lançamentos cadastrados.</div>'}`}
function generateTimeBankReport(){const issue=document.getElementById('timeBankIssueDate')?.value||todayKey(),type=document.getElementById('timeBankReportType')?.value||'simple',source=document.getElementById('timeBankReportSource')?.value||'all',year=timeBankSelectedYear(),people=selectedReportPeople();setPrintMode('timebank');clearPreview();clearReportPreview();clearFrequencyPreview();const sourceLabel=source==='employee'?'Somente funcionários':source==='teacher'?'Somente professores':'Funcionários e professores',subtitle=`Ano ${year} • ${sourceLabel} • Emitido em ${formatDatePt(issue)} • 1 dia = 8h para funcionários e 5h para professores`;let bodies=[];if(type==='simple'){for(let i=0;i<people.length;i+=28){const chunk=people.slice(i,i+28);bodies.push(`<table class="report-table"><thead><tr><th>Nome</th><th>Cargo/Função</th><th>Matrícula</th><th>Total de horas</th><th>Dias e horas</th></tr></thead><tbody>${timeBankSimpleRows(chunk)}</tbody></table>`)}}else{bodies=people.map(timeBankDetailedBody)}document.getElementById('timeBankPrintArea').innerHTML=wrapReportPages(type==='simple'?'BANCO DE HORAS — RESUMO':'BANCO DE HORAS — EXTRATO',subtitle,bodies,'timebank-report');document.getElementById('timeBankControls').style.display='flex';document.getElementById('timeBankCount').textContent=`${people.length} servidor${people.length===1?'':'es'} no relatório`;document.getElementById('timeBankControls').scrollIntoView({behavior:'smooth'})}
function clearTimeBankPreview(){document.getElementById('timeBankPrintArea').innerHTML='';document.getElementById('timeBankControls').style.display='none';document.body.classList.remove('print-timebank')}
function updateHomeNewsForTimeBank(){const list=document.querySelector('.home-news-list');if(!list)return;list.innerHTML='<div class="home-news-item"><span>✓</span><div>Novo controle de Memorandos e Ofícios, com numeração automática por ano.</div></div><div class="home-news-item"><span>✓</span><div>Exportação de cadastros, ocorrências e banco de horas para CSV e Excel.</div></div><div class="home-news-item"><span>✓</span><div>Painel de inconsistências e histórico administrativo das principais alterações.</div></div><div class="home-news-item"><span>✓</span><div>Menu lateral recolhível para ampliar a área de trabalho em telas menores.</div></div>'}
const baseRenderDashboardTimeBank=renderDashboard;
renderDashboard=function(){baseRenderDashboardTimeBank();updateHomeNewsForTimeBank()};
const baseShowViewTimeBank=showView;
showView=function(name){baseShowViewTimeBank(name);if(name==='banco-horas'){renderTimeBankOptions();renderTimeBankSummary();initializeTimeBankForm()}};
const baseRenderAllTimeBank=renderAll;
renderAll=function(){baseRenderAllTimeBank();renderTimeBankOptions();renderTimeBankSummary();initializeTimeBankForm()};
const baseSetPrintModeTimeBank=setPrintMode;
setPrintMode=function(mode){if(mode==='timebank'){document.body.classList.remove('print-points','print-sector','print-birthday','print-registry','print-frequency','print-timebank');document.body.classList.add('print-timebank');document.getElementById('dynamicPrintPage').textContent='@media print{@page{size:A4 portrait;margin:0}}';return}document.body.classList.remove('print-timebank');baseSetPrintModeTimeBank(mode)};
const form=document.getElementById('timeBankForm');if(form){form.addEventListener('submit',saveTimeBankEntry);const personInput=document.getElementById('timeBankPersonSearch');if(personInput){personInput.addEventListener('input',syncTimeBankPersonKey);personInput.addEventListener('change',syncTimeBankPersonKey)}}
window.renderTimeBankReportPeople=renderTimeBankReportPeople;window.generateTimeBankReport=generateTimeBankReport;window.clearTimeBankPreview=clearTimeBankPreview;window.openTimeBankExtract=openTimeBankExtract;window.closeTimeBankExtract=closeTimeBankExtract;window.editTimeBankEntry=editTimeBankEntry;window.deleteTimeBankEntry=deleteTimeBankEntry;
renderAll();resetTimeBankForm();
})();
